name: Deploy to EC2 Windows

on:
  push:
    branches:
      - develop  # Cambiado a tu rama principal (develop)

jobs:
  deploy:
    runs-on: windows-latest  # Se ejecutará en una máquina Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH for Windows
        run: |
          choco install openssh -y
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          RefreshEnv  # Actualizar las variables de entorno después de instalar SSH

      - name: Deploy to EC2
        run: |
          $ErrorActionPreference = 'Stop'
          $pw = ConvertTo-SecureString "qmQ$e%fGO?CCy)J2Yv0MaKY2atHyu;@T" -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ("administrator", $pw)
          $sessionOption = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck
          Invoke-Command -ComputerName "EC2AMAZ-BOT57ES" -Credential $cred -SessionOption $sessionOption -ScriptBlock {
            Set-Location "C:\inetpub\wwwroot\core.deliver.ar"
            git pull origin develop
          }

