name: Deploy to EC2 Windows Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Windows Server
        run: |
          $ErrorActionPreference = 'Stop'

          # Convertir contrase침a a cadena segura
          $password = ConvertTo-SecureString $env:WINDOWS_PASSWORD -AsPlainText -Force

          # Crear objeto de credencial
          $cred = New-Object System.Management.Automation.PSCredential("administrator", $password)

          # Establecer una nueva sesi칩n PSSession
          $session = New-PSSession -ComputerName 54.173.51.17 -Credential $cred -Authentication Default -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck)

          # Verificar si la sesi칩n fue creada exitosamente
          if (-not $session) {
              Write-Error "Failed to create PSSession."
              exit 1
          }

          # Ejecutar comandos en el servidor remoto con registro detallado
          Invoke-Command -Session $session -ScriptBlock {
            try {
              cd C:\inetpub\wwwroot\core.deliver.ar
              Write-Output "Navigated to the target directory."

              if (Test-Path -Path .git) {
                Write-Output "Git repository found. Pulling latest changes."
                git pull origin develop
              } else {
                Write-Output "Git repository not found. Removing existing files and cloning repository."
                Remove-Item -Recurse -Force *
                git clone https://github.com/gerfalasco/xwallet_frontend .
                cd xwallet_frontend
                git checkout develop
              }
            } catch {
              Write-Error "An error occurred during the git operations: $_"
              exit 1
            }
          } -ErrorAction Stop

          # Eliminar la sesi칩n PSSession
          Remove-PSSession -Session $session
        env:
          WINDOWS_PASSWORD: ${{ secrets.WINDOWS_PASSWORD }}

